### ISSUE TITLE
still happening

### ISSUE THREAD

**Issue by rossman22590** [techulus/manage-prompt#125]
still happening

_Originally posted by @rossman22590 in https://github.com/techulus/manage-prompt/issues/107#issuecomment-2282376836_

**Comment by rossman22590** [comment]
prisma error

**Comment by arjunkomath** [comment]
Reopen the issue if it happens while using https://www.prisma.io/data-platform/accelerate

**Comment by rossman22590** [comment]
used fly worked all good ty
