### ISSUE TITLE
Everything is working but getting not answers just all repetition - teste don your site too

### ISSUE THREAD

**Issue by rossman22590** [techulus/manage-prompt#130]
when i run this 

curl --request POST \
     --url https://manageprompt.com/api/v1/run/wf_sycrvybrua6wpj8y7bdx92cr \
     --header 'Authorization: Bearer sk_udssxxxxxxxxxxxxx2nu6ng' \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '"what is VR?"'

response is {
    "success": true,
    "result": "Hello! 😊 How can I assist you today?"
}

shouldn't it tell me about VR?

**Comment by arjunkomath** [comment]
Data should be a JSON object, it will be key-value based on your workflow, for example if your workflow has a input named `topic`, you should pass data as `{"topic":"some-topic"}`

**Comment by rossman22590** [comment]
Doing this results in same answer so confused, I am on your website workflow 118 

https://manageprompt.com/console/workflows/118

![image](https://github.com/user-attachments/assets/336e2167-5c49-4e28-846b-d77b890145a3)

![image](https://github.com/user-attachments/assets/ec69c892-f277-433b-a70e-59d228396843)

![image](https://github.com/user-attachments/assets/28aee824-1f3d-4ac1-85d5-8a75838fef45)

**Comment by rossman22590** [comment]
req - curl --request POST \
  --url https://manageprompt.com/api/v1/run/wf_sycrvybrua6wpj8y7bdx92cr \
  --header 'Authorization: Bearer sk_xxxxxxxxxxxxxxxxxxxxx' \
  --header 'Content-Type: application/json' \
  --data '{"topic":"chat about space"}'


response --- {
    "success": true,
    "result": "Sure, I'd be happy to help! Please provide the topic you're interested in, and I'll give you information related to it."
}

**Comment by arjunkomath** [comment]
This has been fixed by #135, it was caused due to bad caching. I've responded to your support ticket, plus added 1000 credits to your account for testing.
